[changelog]
header = "# Changelog"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | trim }} ({{ commit.hash | truncate(length=7) }})
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

filter_unconventional = false

[git]
tag_pattern = ".*"
