name: Build and Sign APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and tools
        run: |
          apt-get update && apt-get install -y \
            openjdk-17-jdk \
            wget \
            unzip \
            zip \
            && apt-get clean

          wget -q https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O apktool
          wget -q https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.11.1.jar -O apktool.jar
          wget -q https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.1/uber-apk-signer-1.2.1.jar -O uber-apk-signer.jar
          chmod +x apktool
          mv apktool /usr/local/bin/
          mv apktool.jar /usr/local/bin/

          java -version
          apktool --version

      - name: Decode and write keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > build.keystore

      - name: Build APK using apktool
        run: apktool b ./ -o edulink-unsigned.apk

      - name: Check APK contents before signing
        run: unzip -l edulink-unsigned.apk

      - name: Check keystore_password and key_alias length
        run: |
          echo "keystore_password length: ${#KEYSTORE_PASSWORD}"
          echo "key_alias length: ${#KEY_ALIAS}"

      - name: Sign the APK
        run: |
          java -jar uber-apk-signer.jar \
            --apk edulink-unsigned.apk \
            --ks build.keystore \
            --ksAlias "$KEY_ALIAS" \
            --ksPass "$KEYSTORE_PASSWORD" \
            --ksKeyPass "$KEYSTORE_PASSWORD"
    
      - name: Rename signed APK
        run: mv edulink-aligned-signed.apk edulink.apk

      - name: Upload APK to Gitea Release
        uses: https://gitea.com/actions/release-action@main
        with:
          files: edulink.apk
          api_key: '${{ secrets.RELEASE_TOKEN }}'
          tag_name: ${{ steps.tag_version.outputs.VERSION }}
