name: Build and Sign APK

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".gitea/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: apk-builder
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode and write keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > build.keystore

      - name: Build APK using apktool
        run: apktool b ./ -o edulink-unsigned.apk

      - name: Sign the APK
        run: |
          java -jar /usr/local/bin/uber-apk-signer.jar \
            --apk edulink-unsigned.apk \
            --ks build.keystore \
            --ksAlias "$KEY_ALIAS" \
            --ksPass "$KEYSTORE_PASSWORD" \
            --ksKeyPass "$KEYSTORE_PASSWORD"

      - name: Rename signed APK
        run: mv edulink-aligned-signed.apk ../edulink.apk

      - name: Set dynamic tag
        id: tag
        run: |
          TAG="$(date +'%Y-%m-%d-%H-%M-%S')"
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git tag ${{ steps.tag.outputs.tag_name }}
          git push origin ${{ steps.tag.outputs.tag_name }}

      - name: Generate changelog
        run: |
          set -e
          source $HOME/.cargo/env
          git cliff --tag ${{ steps.tag.outputs.tag_name }} > ../changelog.md

      - name: Publish Release on Gitea
        uses: akkuman/gitea-release-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: ${{ steps.tag.outputs.tag_name }}
          body_path: changelog.md
          files: edulink.apk
          prerelease: true
